# Exceptions

- <https://en.cppreference.com/w/cpp/language/exceptions>
- **Exception safety**
  - Nothrow (nofail) exception guarantee
    - 関数が例外を投げない
    - Nothrow (例外は他の方法で通知されるか、隠蔽される)
      - stack unwinding の途中で呼ばれる関数 (destructor...) に期待される
    - Nofail (常に成功する)
      - strong exception guarantee で使用される関数 (swap, move, ...) に期待される
  - Strong exception guarantee
    - 関数が例外を投げた場合、program state は function call 直前まで巻き戻る
    - e.g) `std::vector::push_back`
  - Basic exception guarantee
    - 関数が例外を投げた場合、program は valid state で維持される (リークも無いし、invariant は元のまま)
  - No exception guarantee
    - 関数が例外を投げた場合、program は valid state ではない (不正な状態になっている可能性がある)
  - 一般的な component は exception-neural guarantee を提供する
    - template parameter が例外を投げた場合、そのまま caller に propagate される


## try block

- <https://en.cppreference.com/w/cpp/language/try>
- Function try block
  ```C++
  int f(bool cond)
  {
      if (cond)
          throw 1;
      return 0;
  }

  struct X
  {
      int mem;

      X() try : mem(f(true)) {}
      catch (...)
      {
          // handles the exception 1
      }

      X(int) try
      {
          throw 2;
      }
      catch (...)
      {
          // handles the exception 2
      }
  };
  ```


## Throwing exceptions

- <https://en.cppreference.com/w/cpp/language/throw>
- Constructing and destructing exception objects
  - exception object の type を `T` とすると
  - `obj` の型が `const T` である時、copy initialization が有効
  - `T` が class なら
    - constructor は odr-used
    - destructor は potentially invoked
- **Stack unwinding**
  - exception object が construct されると、try まで stack を遡る
  - stack を遡る最中に automatic duration object の destructor を逆順で呼んでいく
    - 返り値の destructor で例外が発生した場合、その返り値に対する destructor も実行される
  - constructor の中で例外が発生した場合、逆順で解放する
  - new で例外が発生した場合、可能なら deallocate する
  - `std::terminate`


## Handling exceptions

- <https://en.cppreference.com/w/cpp/language/catch>
- TODO


## noexcept specifier

- <https://en.cppreference.com/w/cpp/language/noexcept_spec>
- `noexcept`
- `noexcept(expression)`
  - `expression` が true と評価された場合のみ、`noexcept` になる
- 全ての C++ 関数は non-throwing か potentially throwing
  - TODO
- noexcept 関数ポインタは作成できない
  ```C++
  void ft(); // potentially-throwing
  void (*fn)() noexcept = ft; // error
  ```
- overload/override において、non-throwing / potentially throwing は変更できない


## noexcept operator

- <https://en.cppreference.com/w/cpp/language/noexcept>
- `noexcept(expression)`
  - `expression` が non-throwing なら true を返す
  - compile-time check
